/* ═══════════════════════════════════════════════
   AUTO-GENERATED by scan.py — do not edit manually!
   Run: python scan.py
   Last scan: 2026-03-11T21:15:21
═══════════════════════════════════════════════ */
window.PORTFOLIO_DATA = {
  "images": [
    {
      "id": "img-me",
      "title": "Me",
      "file": "projects/images/me.png",
      "desc": ""
    }
  ],
  "videos": [],
  "socialMedia": [],
  "crypto": [],
  "music": [
    {
      "id": "music-hWakqWRHdzI",
      "title": "Simo - Lone Pulse (Extended)",
      "youtubeId": "hWakqWRHdzI",
      "thumbnail": "https://i1.ytimg.com/vi/hWakqWRHdzI/hqdefault.jpg",
      "publishedAt": "2026-03-01"
    },
    {
      "id": "music-9WRBeVqhApQ",
      "title": "Simo - ACQUA GELIDA (extended remix)",
      "youtubeId": "9WRBeVqhApQ",
      "thumbnail": "https://i2.ytimg.com/vi/9WRBeVqhApQ/hqdefault.jpg",
      "publishedAt": "2026-03-01"
    },
    {
      "id": "music-XhwMA5gi3mo",
      "title": "living in my mind (remake)",
      "youtubeId": "XhwMA5gi3mo",
      "thumbnail": "https://i1.ytimg.com/vi/XhwMA5gi3mo/hqdefault.jpg",
      "publishedAt": "2025-12-10"
    },
    {
      "id": "music-pHbN6JiIgik",
      "title": "Monique",
      "youtubeId": "pHbN6JiIgik",
      "thumbnail": "https://i1.ytimg.com/vi/pHbN6JiIgik/hqdefault.jpg",
      "publishedAt": "2025-12-10"
    },
    {
      "id": "music-pTLuIN26xNw",
      "title": "Ren x Chinchilla - Chalk Outlines (Lo-Fi Remake)",
      "youtubeId": "pTLuIN26xNw",
      "thumbnail": "https://i1.ytimg.com/vi/pTLuIN26xNw/hqdefault.jpg",
      "publishedAt": "2025-11-07"
    }
  ],
  "videoProduction": []
};
